name: TaskWhiz
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  email_validator: ^2.1.17
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  info_popup: ^3.0.6
  audio_service: ^0.18.12
  audioplayers: ^5.1.0
  circular_countdown_timer: ^0.2.3
  path_provider: ^2.1.1
  google_sign_in: ^5.3.3
  firebase_storage: ^11.2.7
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Kablammo
      fonts:
        - asset: fonts/Kablammo-Regular.ttf
    - family: MarckScript
      fonts:
        - asset: fonts/MarckScript-Regular.ttf
    - family: Yantramanav
      fonts:
        - asset: fonts/Yantramanav-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
    - family: SofiaSans
      fonts:
        - asset: fonts/SofiaSans-Regular.ttf
